subspace/protocol-specs

docs/decex/bundles_blocks.md, docs/decex/workflow.md
Modified domain bundle limits as per https://github.com/subspace/subspace/pull/2568/
=> proper bundle limits

docs/decex/interfaces.md, docs/decex/workflow.md
This PR adds more ProofOfElection verification details including the bundle longevity check, which is implemented in https://github.com/subspace/subspace/pull/2586.
=> Add ProofOfElection verification details

docs/crypto_primitives.md, docs/runtime.md
MMR info mostly based on https://www.notion.so/subspacelabs/Merkle-mountain-range-on-Consensus-chain-89a36c6577cb44908b7ac3bdec595e1b?pvs=4 plus a page describing what runtime consists of so it's clear where MMR belongs.
=> MMR and general runtime info

docs/consensus/consensus_chain.md
This PR adds a "Fast sync" paragraph to the synchronization section.
=> Add fast sync description.

docs/consensus/consensus_chain.md, docs/consensus/proof_of_archival_storage.md, docs/fees_and_rewards/Dynamic_Issuance.md, docs/fees_and_rewards/Fees_and_Rewards.md
This PR consists of two paragraphs:
1. Describing the Block Reward Address on the Consensus chain page.
2. Conversion rate between solution range and space pledged (#13 )
=> Block reward address and Conversion rate between space pledged and solution range

docs/decex/fraud_proofs.md, docs/decex/workflow.md
=> Remove bundle equivocation fraud proof

docs/decex/fraud_proofs.md
As per https://github.com/subspace/subspace/pull/2787
Part of #29
=> handle FP with non-existent extrinsic index

docs/decex/workflow.md
We recently introduced Domain Sudo pallet to monorepo in this [PR](https://github.com/subspace/subspace/pull/2884).
This PR adds specific description and flow to execute Sudo calls in Domains.
=> add domain sudo pallet to decex workflow

docs/decex/fraud_proofs.md, docs/decex/xdm.md
Update spec according to the changes introduced in https://github.com/subspace/subspace/pull/2891
=> Update XDM fraud proof spec

docs/decex/workflow.md
dexex spec update to include changes introduced in https://github.com/subspace/subspace/pull/2896
=> update decex workflow to include Sudo operations on domain

docs/decex/bundles_blocks.md, docs/decex/interfaces.md, docs/decex/overview.md, docs/decex/workflow.md
The changes are implemented in https://github.com/autonomys/subspace/pull/2933
=> Add receipt gap changes

docs/decex/staking.md
The changes are implemented in https://github.com/autonomys/subspace/pull/2993
=> Update staking withdraw

docs/decex/staking.md
The change is implemented in https://github.com/autonomys/subspace/pull/3060
=> Update staking spec for the withdrawal limit

docs/consensus/proof_of_archival_storage.md
As per discussion in https://forum.autonomys.xyz/t/change-derivation-of-pospace-seed-and-hdd-compatible-exploit/4438/11
=> move history size from evaluation seed to history size

docs/decex/fraud_proofs.md
This PR updates the fraud proof specification with the changes from https://github.com/autonomys/subspace/issues/3281:
- combine storage proofs for timestamp, moment, and storage fees,
- replace multiple consensus chain storage fee inputs with the derived consensus byte storage fee, and
- replace block randomness with the derived extrinsics shuffling seed.
It also updates the spec for a previously undocumented change which added the domain sudo call extrinsic.
The PRs for ticket https://github.com/autonomys/subspace/issues/3281 also:
- replaced the block digest storage proof with a list of upgraded runtime IDs,
- fixed an implementation bug in the storage fee calculation, and
- rearranged some struct fields,
but that's a level of detail which isn't needed in the spec.
=> Update invalid inherent fraud proof with combined storage

docs/decex/xdm.md
This PR updates some of the outdated XDM changes from the following commit: https://github.com/autonomys/subspace/commit/0b9be7c670888399b950b87b89fc6a9421acc35e
=> update xdm specs

docs/decex/interfaces.md, docs/decex/private_evm.md, docs/decex/xdm.md, docs/runtime.md
This PR documents how Private EVM works at the pallet and runtime levels.
It also documents some context for EVM runtimes.
See also https://github.com/autonomys/subspace/pull/3350
=> Add Private EVM spec

docs/decex/xdm.md
PR adds the missing XDM runtime calls
=> add xdm runtime calls

docs/decex/interfaces.md, docs/decex/private_evm.md
This PR updates the specs now that PR https://github.com/autonomys/subspace/pull/3381 has merged.
=> Update specs for public/private EVM setting and domain owner call

docs/decex/staking_arithmetic_dust.md
This PR adds a doc about the staking arithmetic dust analysis
=> Add staking arithmetic dust doc
